# Generated by scripts/theme from themes/<name>.conf -- edit the palette, not this.
# kitty.conf includes this at its end, so these win over anything above.

background            #{{ bg }}
foreground            #{{ fg }}
cursor                #{{ accent }}
selection_background  #{{ muted }}
selection_foreground  #{{ fg }}
url_color             #{{ accent }}

active_border_color   #{{ accent }}
inactive_border_color #{{ muted }}
active_tab_background #{{ accent }}
active_tab_foreground #{{ bg }}
inactive_tab_background #{{ chip }}
inactive_tab_foreground #{{ dim }}
