# Generated by scripts/theme from themes/<name>.conf -- edit the palette, not this.
# Included from ghostty/config, and it replaces the named theme= line: a theme
# name only exists for palettes ghostty ships, which ours will not always be.

background = {{ bg }}
foreground = {{ fg }}
cursor-color = {{ accent }}
selection-background = {{ muted }}
selection-foreground = {{ fg }}
