-- Generated by scripts/theme from themes/<name>.conf -- edit the palette.
-- A table rather than a templated hyprland.lua: that file is edited constantly
-- and should not become a build artefact.
return {
  border_from = "rgba({{ border_active_from }}cc)",
  border_to   = "rgba({{ border_active_to }}cc)",
  border_off  = "rgba({{ border_inactive }}aa)",
  shadow      = "rgba({{ shadow }}ee)",
}
