-- Generated by scripts/theme from themes/<name>.conf -- edit the palette.
--
-- aether is a colorscheme that takes its palette as options, so one plugin
-- renders every theme. The alternative is a colorscheme plugin per theme, which
-- means only the handful you have installed can ever be shown.
--
-- lazy loads this from dotbase/nvim/lua/plugins/theme.lua, which prefers this
-- file when Dotnux is present and falls back to catppuccin when it is not.
return {
  {
    "bjarneo/aether.nvim",
    branch = "v3",
    name = "aether",
    priority = 1000,
    opts = {
      colors = {
        bg = "#{{ bg }}",
        dark_bg = "#{{ bar_bg }}",
        darker_bg = "#{{ shadow }}",
        lighter_bg = "#{{ chip }}",

        fg = "#{{ fg }}",
        dark_fg = "#{{ dim }}",
        light_fg = "#{{ light_fg }}",
        bright_fg = "#{{ fg }}",
        muted = "#{{ muted }}",

        red = "#{{ urgent }}",
        yellow = "#{{ warn }}",
        orange = "#{{ orange }}",
        green = "#{{ ok }}",
        cyan = "#{{ cyan }}",
        blue = "#{{ blue }}",
        magenta = "#{{ magenta }}",
        brown = "#{{ orange }}",

        bright_red = "#{{ urgent }}",
        bright_yellow = "#{{ warn }}",
        bright_green = "#{{ ok }}",
        bright_cyan = "#{{ cyan }}",
        bright_blue = "#{{ blue }}",
        bright_magenta = "#{{ magenta }}",

        accent = "#{{ accent }}",
        cursor = "#{{ accent }}",
        foreground = "#{{ fg }}",
        background = "#{{ bg }}",
        selection = "#{{ muted }}",
        selection_foreground = "#{{ fg }}",
        selection_background = "#{{ muted }}",
      },
    },
    config = function(_, opts)
      require("aether").setup(opts)
      vim.cmd.colorscheme("aether")
    end,
  },
}
