-- Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/Start/

-- Omarchy's bootstrap keeps path setup out of this user config.
dofile((os.getenv("OMARCHY_PATH") or "/usr/share/omarchy") .. "/default/hypr/bootstrap.lua")

-- Disable all Omarchy default bindings. Add your own in hypr/bindings.lua.
-- Only tiling.lua is actually being replaced: hypr/bindings.lua re-requires the
-- media, clipboard, utilities, voxtype and applications modules.
omarchy_default_bindings = false
--
-- Or disable only bindings for Omarchy's preinstalled apps/web apps while
-- keeping core window-manager bindings:
-- omarchy_preinstalled_bindings = false

-- Load Omarchy defaults.
require("default.hypr.omarchy")

-- Put your personal overrides in these files. They're loaded after Omarchy's
-- defaults so package updates can improve the defaults without rewriting your
-- ~/.config/hypr files.
require("hypr.monitors")
require("hypr.input")
require("hypr.bindings")
-- dwm-style per-monitor tags, replacing the digit and wheel binds that used to
-- live in bindings.lua. Must come after monitors.lua, whose descriptions it
-- matches on.
--
-- workspace-tags.lua is GENERATED by the Workspace Tags bar widget
-- (~/.config/omarchy/plugins/chagel.workspace-tags, a link into
-- ~/Work/omarchy/omarchy-workspace-tags). Edit it from the widget's own panel,
-- not by hand; saving there rewrites the file and reloads Hyprland. It is
-- deliberately not tracked in this repo: it is build output, and the settings
-- it is built from live in configs/omarchy/shell.json.
--
-- require_optional, not require: that file only exists once the widget has been
-- opted in, and a require that cannot find its module throws -- which abandons
-- the rest of this file, taking looknfeel and autostart with it. This is a
-- no-op while the file is absent and still reports real errors from one that is
-- there. Still a require underneath, which matters: bootstrap.lua clears
-- package.loaded for the `hypr` prefix on every reload, so a regenerated file
-- is re-read rather than served from the module cache.
require("hypr.looknfeel")
require("hypr.autostart")

-- Toggle config flags dynamically.
require("default.hypr.toggles")

-- Add any other personal Hyprland configuration below.
-- o.window("qemu", { workspace = "5" })

-- The dictionary is a lookup, not a window to manage: float and centre it.
-- omarchy's own rules only tag org.omarchy.* as terminals, they do not float
-- them, so this is ours to say.
o.window("org.omarchy.define", { float = true })
o.window("org.omarchy.define", { center = true })
o.window("org.omarchy.define", { size = { 900, 520 } })

















-- workspace-tags:begin  (managed by the Workspace Tags widget)
require("default.hypr.require_optional").module("hypr.workspace-tags")
-- workspace-tags:end
